[env]
PROFILE = { value = "release", condition = { env_not_set = ["PROFILE"] } }
TARGET_NAME = "fuzzer"
TARGET_DIR = "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}"
TARGET_DEFINE = "TARGET_SYNC_EXIT"
KERNEL_NAME = "" # Should be defined by extending according to the kernel
KERNEL_DIR = "${CARGO_MAKE_WORKING_DIRECTORY}/kernel/${KERNEL_NAME}"
# LibAFL congiuration
LLVM_CONFIG = "15" # Not necessary, but specify if you encounter "LLVM not found" error
LIBAFL_QEMU_DIR = "${HOME}/os/qemu-libafl-bridge"

# Templates to be extended

# Default: build with make and extra flags
[tasks.kernel]
script_runner = "@shell"
script = """
make -C ${KERNEL_DIR} \
    CFLAGS_EXTRA="-D ${TARGET_DEFINE} -I${TARGET_DIR}/${PROFILE}/include" \
"""

# Default: do nothing
[tasks.kernel_image]
dependencies = ["kernel"]
script_runner = "@shell"
script = """
echo "Task kernel_image has nothing to do."
"""

[tasks.dummy_image]
condition = { files_not_exist = [ "${TARGET_DIR}/dummy.qcow2" ] }
script_runner = "@shell"
script = """
qemu-img create -f qcow2 ${TARGET_DIR}/dummy.qcow2 32M
"""

[tasks.build_fuzzer]
command = "cargo"
args = [
    "build",
    "--profile", "${PROFILE}",
    "--target-dir", "${TARGET_DIR}",
    "-v",
]

# This task is to simplify the work for extending by defining all the dependencies.
[tasks.run_fuzzer_base]
dependencies = ["build_fuzzer", "kernel", "kernel_image", "dummy_image"]

# This task should be defined by extending according to the kernel.
[tasks.run_fuzzer]
dependencies = ["run_fuzzer_base"] # You should add this line when extending.
script = """
echo "Error: Task run_fuzzer should be overridden. Exiting..."
exit 1
"""

# For users

[tasks.build]
command = "cargo"
args = [
    "make",
    "--makefile", "$makefiles/${KERNEL_NAME}.toml",
    "build_fuzzer", # Don't call build!
]

[tasks.run]
command = "cargo"
args = [
    "make",
    "--makefile", "makefiles/${KERNEL_NAME}.toml",
    "run_fuzzer", # Don't call run!
]

[tasks.default]
alias = "run"

[tasks.clean]
clear = true
script_runner = "@shell"
script = """
cargo clean
rm -rf ${CARGO_MAKE_CRATE_TARGET_DIRECTORY}
make clean -C ${KERNEL_DIR}
"""
