[env]
# Profile
PROFILE = { value = "release", condition = { env_not_set = ["PROFILE"] } }
FEATURE = { value = "", condition = { env_not_set = ["FEATURE"] } }

# Fuzzer
TARGET_NAME = "fuzzer"
TARGET_DIR = "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}"
TARGET_DEFINE = "TARGET_SYNC_EXIT"

# Kernel
KERNEL_NAME = "" # Should be defined according to the kernel
KERNEL_DIR = ""  # Should be defined according to the kernel

# LibAFL congiuration
# Not necessary, but specify if you encounter "LLVM not found" error
# Ref: https://github.com/AFLplusplus/LibAFL/blob/b9cfcf07710e189bbd95dd274b893c1d59d4f24a/libafl_qemu/libafl_qemu_build/src/lib.rs#L89
# LLVM_CONFIG = "15"
# Specify if you are using your own version of qemu-libafl-bridge
# LIBAFL_QEMU_DIR = "${HOME}/os/qemu-libafl-bridge"

# Build fuzzer
[tasks.build_fuzzer]
command = "cargo"
args = [
    "build",
    "--features", "${FEATURE}",
    "--profile", "${PROFILE}",
    "--target-dir", "${TARGET_DIR}",
    "-v",
]

# Clean fuzzer
[tasks.clean_fuzzer]
command = "cargo"
args = ["clean"]

# NOTE: This is an empty task, you should define it according to the kernel
[tasks.build_kernel]

# NOTE: This is an empty task, you should define it according to the kernel
[tasks.clean_kernel]

[tasks.default]
alias = "run"

[tasks.build]
clear = true
dependencies = ["build_fuzzer", "build_kernel"]

# NOTE: No commands are defined for the run task, you should define it according to the kernel
[tasks.run]
clear = true
dependencies = ["build"]

[tasks.clean]
clear = true
dependencies = ["clean_fuzzer", "clean_kernel"]
