extend = "../Makefile.toml"

[env]
KERNEL_NAME = "helloworld_os"

[tasks.run_fuzzer]
clear = true
dependencies = ["run_fuzzer_base"]
command = "${TARGET_DIR}/${PROFILE}/${TARGET_NAME}"
args = [
    "--",
    # "-machine", "q35", # q35 not working
    "-kernel", "${KERNEL_DIR}/build/kernel.bin",
    "-drive", "if=none,format=qcow2,file=${TARGET_DIR}/dummy.qcow2",
    "-L", "/usr/local/share/qemu",
    "-nographic",
]