extend = "../Makefile.toml"

[env]
KERNEL_NAME = "rCore-Tutorial-v3"
KERNEL_DIR = "${CARGO_MAKE_WORKING_DIRECTORY}/kernel/${KERNEL_NAME}/os"
KERNEL_ELF = "${KERNEL_DIR}/target/riscv64gc-unknown-none-elf/release/os"
KERNEL_BIN = "${KERNEL_ELF}.bin"
KERNEL_ENTRY_PA = 0x80200000
FS_IMG = "${KERNEL_DIR}/../user/target/riscv64gc-unknown-none-elf/release/fs.img"
RUSTUP_TOOLCHAIN = "" # clear env

[tasks.kernel]
script_runner = "@shell"
script = """
make -C ${KERNEL_DIR} build
"""

[tasks.run_fuzzer]
clear = true
dependencies = ["run_fuzzer_base"]
command = "${TARGET_DIR}/${PROFILE}/${TARGET_NAME}"
args = [
    "--",
    "-machine", "virt",
    "-nographic",
    "-bios", "${KERNEL_DIR}/../bootloader/rustsbi-qemu.bin",
    "-device", "loader,file=${KERNEL_BIN},addr=${KERNEL_ENTRY_PA}",
    # "-D", "qemu-rcore.log",
    # "-d", "in_asm,int,cpu_reset,guest_errors,op_opt",
]
