extend = "../Makefile.toml"

[env]
KERNEL_NAME = "xv6-x86_64"

[tasks.kernel_image]
script_runner = "@shell"
script = """
qemu-img convert -f raw -O qcow2 ${KERNEL_DIR}/xv6.img ${KERNEL_DIR}/xv6.qcow2
qemu-img convert -f raw -O qcow2 ${KERNEL_DIR}/fs.img ${KERNEL_DIR}/fs.qcow2
"""

[tasks.run_fuzzer]
clear = true
dependencies = ["run_fuzzer_base"]
command = "${TARGET_DIR}/${PROFILE}/${TARGET_NAME}"
args = [
    "--",
    "-nic", "none",
    "-drive", "file=${KERNEL_DIR}/fs.qcow2,index=1,media=disk",
    "-drive", "file=${KERNEL_DIR}/xv6.qcow2,index=0,media=disk",
    "-drive", "if=none,format=qcow2,file=${TARGET_DIR}/dummy.qcow2",
    "-L", "/usr/local/share/qemu",
    "-smp", "1",
    "-m", "256",
    "-nographic",
]
