extend = "../Makefile.toml"

[env]
KERNEL_NAME = "xv6-riscv"
KERNEL_DIR = "${CARGO_MAKE_WORKING_DIRECTORY}/kernel/${KERNEL_NAME}"

[tasks.build_kernel]
command = "make"
args = [
    "-C", "${KERNEL_DIR}",
    "kernel/kernel", "fs.img",
    "CFLAGS_EXTRA=\"-D ${TARGET_DEFINE} -I${TARGET_DIR}/${PROFILE}/include\"",
]

[tasks.clean_kernel]
command = "make"
args = ["-C", "${KERNEL_DIR}", "clean"]

[tasks.run]
command = "${TARGET_DIR}/${PROFILE}/${TARGET_NAME}"
args = [
    "--",
    "-machine", "virt",
    "-bios", "none",
    "-kernel", "${KERNEL_DIR}/kernel/kernel",
    "-m", "128M",
    "-smp", "1",
    "-nographic",
    "-global", "virtio-mmio.force-legacy=false",
    "-drive", "file=${KERNEL_DIR}/fs.img,if=none,format=raw,id=x0",
    "-device", "virtio-blk-device,drive=x0,bus=virtio-mmio-bus.0",
    # "-D", "qemu-xv6.log",
    # "-d", "in_asm,int,pcall,cpu_reset,guest_errors",
]
